## Allow Ingress Only from Frontend Pods
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend
  namespace: dev
spec:
  podSelector:
    matchLabels:
      app: backend                 ## Target pods (backend)
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: frontend            ## Allow traffic from pods with label frontend
    ports:
    - protocol: TCP
      port: 80                     ## Allow only port 80
